### ISSUE TITLE
Regarding to the number of labels in each client

### ISSUE THREAD

**Issue by dino-chiio** [Sapienza-University-Rome/FedArtML#1]
I am researching your library for federated learning. This is an amazing tool.

However, when creating the clients's datasets, can we create the clients that include different numbers of labels? For example, Client 1 includes 5 labels: 0, 1, 2, 3, 5. Meanwhile, client 2 includes 3 labels: 2, 7, 8.

**Comment by damjimenezgu** [comment]
@dino-chiio , thanks for your interest in our library, and sorry for the late reply. Unfortunately, you can't choose exactly which classes should go to one or another client. With our tool, you can try to create the clients the way you need by using the "Percent of non-IID-ness method" and setting the parameter as percent_noniid = 100. You can check if this is enough for you by checking and modifying the following example:

https://github.com/Sapienza-University-Rome/FedArtML/blob/master/examples/04_Get_started_create_FL_data_label_skew_percent_noniid_Physionet.ipynb

Let me know if we can help you somehow.
